### ISSUE TITLE
SEO Dashboard - Search Team Member Performance Dashboard

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#103]
Can the dashboard reflect "last weeks" data in addition to"this week"? I mainly use this dashboard on Mondays to retrieve the previous week's data. See Lindsey with questions.

**Comment by ahuensch** [comment]
Hey Lindsey - 

So I can do this...but you can only have 20 dashboard components so we will have to eliminate some since we're already at 18.

That being said, I can schedule a report to send to you every Monday morning.  Which might actually be better.  I use these a lot so I don't have to remember to take a snapshot. 

I've tentatively scheduled the following report to be sent to you every Monday at 5AM.  Let me know what you think :)

Scheduled Weekly Performance Snapshot
https://na13.salesforce.com/00Oa0000008nQN5?newid=00Oa0000008nQN5

Cheers, 
Anna
