### ISSUE TITLE
New Client Services Outreach Project

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#130]
Anna - the Customer Support team is doing an outreach to current customers without responsive designs that haven't had any activity on their account in over 6 months.  Once I get you a list I will want to create cases so that I can assign them to the reps.

**Comment by officite** [comment]
I am going to have them try 3 calls and do a marketing email.  Prior to creating the cases I'll want to sit down with you to discuss the process.

**Comment by officite** [comment]
Also - want to make sure it is clear to sales that we made these calls - not sure the best way to notify them.

**Comment by officite** [comment]
I'm going to send you over a list today.

**Comment by ahuensch** [comment]
What happens if I client is interested in purchasing a responsive design
template?

On Tue, Aug 18, 2015 at 11:02 AM, officite <notifications@github.com> wrote:

> I'm going to send you over a list today.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ahuensch/officite/issues/130#issuecomment-132260201>.
>



-- 
*Anna Huensch*
1546 North LaSalle, Chicago, IL 60610
t *630.639.1960*

**Comment by officite** [comment]
We would select Design Upgrade as the asset and put in the corresponding rate (we have a tiered structure, with some being done for free).  Case would then get closed out.

**Comment by ahuensch** [comment]
Okay cool.

Below are a couple of things that come to mind, you may want to consider.

*1) Generating an asset requires creating an opportunity and service
agreement *(even if they are FREE)

If Client Service Reps will be entering orders, they will require:

   - Training on entering an opportunity / service agreement
   - Revised permissions to allow the access to the records required to
   perform order entry

If not, what will the process be for handing off order entry information?

*2) Our sales process was built to monitor potential sales as Leads not
Cases*

Leads support the following functions

   - Logging # tasks completed (calls/emails/demos)
   - Convert directly into opportunity on existing account
   - Tracks primary campaign source

While CS may be most comfortable with case records, I HIGHLY suggest using
leads instead of cases. This will make it easier for sales and marketing to
measure the success of your efforts :)






On Tue, Aug 18, 2015 at 1:47 PM, officite <notifications@github.com> wrote:

> We would select Design Upgrade as the asset and put in the corresponding
> rate (we have a tiered structure, with some being done for free). Case
> would then get closed out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ahuensch/officite/issues/130#issuecomment-132315463>.
>



-- 
*Anna Huensch*
1546 North LaSalle, Chicago, IL 60610
t *630.639.1960*

**Comment by officite** [comment]
Sorry - got distracted today.  Let me review your thoughts tomorrow and then we can come up with a move forward strategy.

Fred
