### ISSUE TITLE
Consolidate quarterly updates and monthly health checks in active SEO programs

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#18]
Currently, on the SEO report for each search specialist, "quarterly update" and "health check" are two separate action items. As a result, some months display two action items for one client.

We decided that the quarterly update email can be the health check for that month to condense the reporting. Is there a way to create logic on the reporting that for any client that has a health check AND a quarterly update due, that only quarterly update displays on the report? 

Also, since quarterly update email is the health check, is there a way that for the months were both are due, that when the quarterly action item is closed, the health check action item closes automatically? See Lindsey for questions.

**Comment by ahuensch** [comment]
Consolidated Quarterly Updates & Monthly Health Checks within all SEO Programs

Quarterly updates are now denoted as an icon on monthly health checks.  Icon will appear 90 days after the last completed quarterly update and/or health check where quarterly update is present. 

Updated the below report to include the icon so Search Specialists can quickly see which tasks will require a quarterly update yes/no. 

My Open SEO Maintenance Tasks
https://na13.salesforce.com/00Oa0000007xsUi

Please note - If a search specialist sends a quarterly update with a health check out of sequence, please have them check the box "Include Quarterly Update" on the Monthly Health Check so that the algorithm determining the last quarterly update recalculates. 

Let me know if you have any additional questions / concerns / issues. 

Cheers, 
Anna
