### ISSUE TITLE
Review SEO reporting changes with Lindsey

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#58]
The reporting changed for "Monthly Health Check + Update" and I (Lindsey) don't understand it. Can you explain when you get a chance: https://na13.salesforce.com/00Oa0000008mgwG?dbw=1

Thank you!

**Comment by ahuensch** [comment]
Hi Lindsey -

No problem.   A lot of things changed when we changed the dashboard
components and updated quarterly updates to be part of monthly health
checks.

To make sure I explain the right thing can you elaborate what is new or
confusing?

Also if it would be helpful, we can set a time to chat too.

Cheers,
Anna

-- 
*Anna Huensch*
1546 North LaSalle, Chicago, IL 60610
t *630.639.1960*

On Mon, Jul 6, 2015 at 9:29 AM, officite <notifications@github.com> wrote:

> The reporting changed for "Monthly Health Check + Update" and I (Lindsey)
> don't understand it. Can you explain when you get a chance:
> https://na13.salesforce.com/00Oa0000008mgwG?dbw=1
>
> Thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ahuensch/officite/issues/58>.
>



-- 
*Anna Huensch*
1546 North LaSalle, Chicago, IL 60610
t *630.639.1960*

**Comment by ahuensch** [comment]
Sure thing. Does the report only display the number of quarterly update
emails or the total of update emails and individual health checks?

I was also confused because the report displays a number of adwords health
checks as well. So wasn't sure how much data was on that report.

Let me know if that doesn't make sense!

Thanks,

Lindsey

*Lindsey Albanese* *|* Officite *|**Search Team Manager*
3010 Highland Parkway | Suite 625 | Downers Grove, IL 60515
t 630.230.2330 Ext. 2362  | *lalbanese@officite.com
<lalbanese@officite.com>*

**Comment by ahuensch** [comment]
This report summarizes Monthly Health Checks and AdWords Health Checks due this month.  Quarterly updates are no longer their own discrete task, but rather just a flavor of Monthly Health Check.  

I added an extra summary field to the report to raise visibility on which ones include quarterly updates (the ones with the checked check box).  Let me know if there is anything else I can do. 

Cheers, 
Anna
