### ISSUE TITLE
Facilitate proactively reaching out to customers aged 2-4 years

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#70]

**Comment by officite** [comment]
Hi Anna,

We are looking to start an outbound call / marketing campaign to get ahead of cancellations.  From our data, we know that clients are cancelling services with us between the 2 - 4-year mark.   Therefore, we want to reach out to them prior to cancellation to see what we can do for them in the way of a design upgrade, additional services, etc. Hopefully a fresh website, personal touch and maybe a new service or two will keep our clients on with us.

We want to build a report - if you have other thoughts to help drive this, please jump in!

contact list to include
- AOP
- Monthly recurring
- Date of last case w number of days to close
- Date of last activity history *

*With the last activity case, we feel that sometimes this may not be the right case to look at as there is so much in this section.  Is there another way to look at this to pull the most valuable data in here to help us with our list?

Thank you!

Patti

**Comment by ahuensch** [comment]
Hi Patti - 

Because the target audience for this initiative is so large.  I would suggest coming up with a series of small target groups to pull data.  Target groups with 100-300 people that your cancellation research indicates are the most likely to cancel.  This should help surface the highest priority folk worth reaching out to.  

Then respective to the target audience I would pull relevant data to internally prioritize outbound calls to that group. 

For example: Group 1
Dental customers aged 2-4 years with custom work cases closed overdue greater than 45 days with average recurring greater than $100/mo. 
 
Have you guys decided how you'll be tracking your progress?   Should we standardize how you log activities?  i.e. set a specific contact method / reason? 

I setup a report folder for this initiative to show the entire audience.  Once we setup a standard for tracking outbound calls, we can update the report's filter criteria to drop off names as we reach out to them

CS: Retention Initiative

Active Accounts Aged 2-4 Years
https://na13.salesforce.com/00Oa0000008nOo9
